name = "DJ's Theme (Fork of Black and Light)"
license = "GNU3.0"
licenselink = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme/blob/master/LICENSE"
description = "A High contrast, text oriented, performant and Javascript-free theme for Hugo. "
homepage = "https://github.com/thesomamyth/hugo-black-and-light-theme"
tags = ["responsive", "minimal", "simple", "personal", "white"]
min_version = "0.65.0"

